{"name": "test_invalid_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'driver'", "trace": "self = <test_login.TestLogin object at 0x0000022403075A60>\n\n    @pytest.mark.usefixtures(\"setup\")\n    def test_invalid_login(self):\n>       self.driver.get(\"https://www.saucedemo.com/\")\nE       AttributeError: 'TestLogin' object has no attribute 'driver'\n\ntests\\test_login.py:25: AttributeError"}, "start": 1725442291076, "stop": 1725442291076, "uuid": "94b0691e-9cea-42c8-b0f6-9fda8cd67e1d", "historyId": "5ad05e7b3e746de3eeebc71b61c34a27", "testCaseId": "5ad05e7b3e746de3eeebc71b61c34a27", "fullName": "tests.test_login.TestLogin#test_invalid_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS"}, {"name": "thread", "value": "4288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}