{"name": "test_invalid_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'driver'", "trace": "self = <test_login.TestLogin object at 0x000002D6BA6455B0>\n\n    @pytest.mark.usefixtures(\"setup\")\n    def test_invalid_login(self):\n>       self.driver.get(\"https://www.saucedemo.com/\")\nE       AttributeError: 'TestLogin' object has no attribute 'driver'\n\ntests\\test_login.py:25: AttributeError"}, "start": 1725442047893, "stop": 1725442047893, "uuid": "e4271539-1dd0-45bb-bfb4-4a96c6fdcd15", "historyId": "5ad05e7b3e746de3eeebc71b61c34a27", "testCaseId": "5ad05e7b3e746de3eeebc71b61c34a27", "fullName": "tests.test_login.TestLogin#test_invalid_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS"}, {"name": "thread", "value": "24464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}